#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5
ENV_FILE=".env.local"
RESULTS_FILE="docs/archive/scratch/smart-layer-map-2026-08/research/11-key-verification.md"

banner "Anthropic account + API key for Atlas (ticket 11)"

# ── Stage 1: the account and org ──────────────────────────────────────────
stage "Anthropic Console — create the account and org"
say "Atlas needs its own Anthropic org (third LLM vendor, after Gemini and OpenAI)."
say "This is a paid API account — separate from any claude.ai subscription."
open_url "https://platform.claude.com/"
step "Sign up (or sign in) — use the Atlas email: timlulproduct@gmail.com."
step "If it asks for an organization name, use: Atlas."
note "If the page redirects you through console.anthropic.com, that's the same Console."
pause "Signed in and looking at the Console dashboard? Press Enter."

# ── Stage 2: billing ──────────────────────────────────────────────────────
stage "Billing — payment method + first credits"
say "A new org starts in an Evaluation tier; adding billing and buying credits"
say "is what moves it onto the Start tier (1,000 RPM, \$500/month spend cap)."
step "In the Console, open Settings → Billing (left sidebar or org menu)."
step "Add a payment method."
step "Buy an initial credit balance — \$25 is plenty for prototyping."
step "Recommended: enable auto-reload with a LOW threshold (e.g. reload \$25 at \$5)"
step "so experiments never die mid-run, but a runaway bug can't burn much."
pause "Billing set up? Press Enter."

# ── Stage 3: the API key ──────────────────────────────────────────────────
stage "API key — create and store locally"
step "In the Console, open Settings → API Keys."
step "Click 'Create Key'. Name it: atlas-server"
step "Copy the key NOW — it is shown only once (starts sk-ant-)."
ask_secret ANTHROPIC_API_KEY "Paste the key (input hidden):"
write_env ANTHROPIC_API_KEY "$ANTHROPIC_API_KEY"
note "Written to .env.local, which is git-ignored — it will never be committed."

# ── Stage 4: Railway ──────────────────────────────────────────────────────
stage "Railway — add the key to the production environment"
say "The deployed app (www.timlul-ai.com) needs the same key as a Railway variable."
open_url "https://railway.app/dashboard"
step "Open the Atlas project → the web service → Variables tab."
step "Add a new variable:  ANTHROPIC_API_KEY  =  (paste the same key)"
warn "Saving a variable triggers a redeploy of the service — do it when nobody is mid-demo."
if confirm "Added the variable on Railway (or deliberately deferring it)?"; then
  say "Noted."
else
  SKIPPED+=("Railway variable ANTHROPIC_API_KEY — add it in the service's Variables tab")
  warn "Recorded as still-to-do; local dev works either way."
fi

# ── Stage 5: verify + record the tier ─────────────────────────────────────
stage "Verify the key + record the rate-limit tier"
say "Running one tiny metered call (fractions of a cent) plus a free count_tokens"
say "re-baseline of Hebrew token arithmetic. No secrets are written to the results file."
if node scripts/anthropic-verify.mjs; then
  say ""
  step "Now check the official tier: in the Console, open Settings → Limits."
  step "It shows the org's usage tier and monthly spend cap."
  ask RATE_TIER "Type the tier exactly as shown (e.g. 'Start, \$500/month cap'):"
  {
    printf '\n## Founder-confirmed tier (Console → Settings → Limits)\n\n%s\n' "$RATE_TIER"
  } >> "$RESULTS_FILE"
  say "Recorded in $RESULTS_FILE."
else
  SKIPPED+=("Verification failed — re-run: node scripts/anthropic-verify.mjs")
  warn "The metered call failed. Fix the key (or billing) and re-run the verify script."
fi
# ──────────────────────────────────────────────────────────────────────────

finish
say "Next: tell the Claude session the wizard is done — it will file ticket 11's answer."
